name: bnx-os
description: Mon système Fedora Kinoite (Pur) optimisé avec KineticWE
# L'image officielle de Fedora Kinoite, sans les altérations d'Universal Blue
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

modules:
  - type: rpm-ostree
    repos:
      # Les liens .repo texte vont ici
      - https://copr.fedorainfracloud.org/coprs/linuxgamerlife/lgl-experimental/repo/fedora-44/linuxgamerlife-lgl-experimental-fedora-44.repo
      - https://repo.librewolf.net/librewolf.repo
    
    remove:
      - firefox
      - firefox-langpacks

    install:
      # Les paquets d'activation RPM Fusion (.rpm) vont ici
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-44.noarch.rpm
      
      # Navigateur natif
      - librewolf
      
      # Environnement et outils CLI
      - kineticwe
      - kitty
      - fish
      - neovim
      - stow
      - git
      
      # Gaming natif et optimisation
      - steam
      - gamemode
      - mangohud
      - steam-devices

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: script
    snippets:
      - "chsh -s /usr/bin/fish"
