name: bnx-os
description: Mon système Bazzite (Steam natif) avec KineticWE et LibreWolf
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: rpm-ostree
    repos:
      # Dépôt KineticWE avec la version 44 fixée
      - https://copr.fedorainfracloud.org/coprs/linuxgamerlife/lgl-experimental/repo/fedora-44/linuxgamerlife-lgl-experimental-fedora-44.repo
      # Dépôt officiel LibreWolf
      - https://repo.librewolf.net/librewolf.repo
    
    remove:
      # Nettoyage du navigateur par défaut
      - firefox
      - firefox-langpacks

    install:
      # Navigateur natif
      - librewolf
      
      # Environnement et outils CLI
      - kineticwe
      - kitty
      - fish
      - neovim
      - stow
      - git

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: script
    snippets:
      - "chsh -s /usr/bin/fish"
