name: bnx-os
description: Mon système Bazzite optimisé avec KineticWE
# On utilise l'image Bazzite (KDE) qui a déjà Steam et les optimisations gaming
base-image: ghcr.io/ublue-os/bazzite
image-version: 44

modules:
  - type: rpm-ostree
    repos:
      # L'URL COPR avec la variable %OS_VERSION% (votre excellente syntaxe !)
      - https://copr.fedorainfracloud.org/coprs/linuxgamerlife/lgl-experimental/repo/fedora-%OS_VERSION%/linuxgamerlife-lgl-experimental-fedora-%OS_VERSION%.repo
    
    install:
      # On installe UNIQUEMENT vos outils spécifiques.
      # Steam, gamemode, mangohud et steam-devices sont retirés d'ici car Bazzite les a déjà.
      - kineticwe
      - kitty
      - fish
      - neovim
      - stow
      - git

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: script
    snippets:
      - "chsh -s /usr/bin/fish"
